### ISSUE TITLE
Setup automatic CI/CD in GitHub Actions

### ISSUE THREAD

**Issue by warezeada** [warezeada/thesis-epics#3]
- [x] https://github.com/warezeada/thesis-project-backend/issues/3
- [x] https://github.com/warezeada/thesis-project-backend/issues/4
- [x] https://github.com/warezeada/thesis-project-frontend/issues/3
